name: CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          heroku apps:info --app cmarshal
          heroku container:login
          docker build . -t registry.heroku.com/cmarshal/web
          docker push registry.heroku.com/cmarshal/web

